async function afficherCity() {
    const response = await fetch ("https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/${$filter=adress eq 'Tokyo,Japan' or adress eq 'Osaka,Japan' or adress eq 'Yokohama,Japan' or adress eq 'Nagoya,Japan' or adress eq 'Sapporo,Japan' or adress eq 'Kobe,Japan' or adress eq 'Kyoto,Japan' or adress eq 'Fukuoka,Japan'}?unitGroup=metric&key=EMMSPMZNCSEFKYYZ3GZ8LYVBR&contentType=json");
    const city = await response.json();
    console.log(city);
  }
  afficherCity();

  /*==> sans (city.resolvedAddress)rez ==
  
  [Running] node "/Users/Mathilde/Ada_Git/projet-collectif-dataviz-dataviz_production/script.js"
  {
    queryCost: 1,
    latitude: 41.0497,
    longitude: 141.253,
    resolvedAddress: 'Yokohama, Japan',
    address: "${$filter=adress eq 'Tokyo,Japan' or adress eq 'Osaka,Japan' or adress eq 'Yokohama,Japan' or adress eq 'Nagoya,Japan' or adress eq 'Sapporo,Japan' or adress eq 'Kobe,Japan' or adress eq 'Kyoto,Japan' or adress eq 'Fukuoka,Japan'}",
    timezone: 'Asia/Tokyo',
    tzoffset: 9,
    description: 'Similar temperatures continuing with a chance of rain today, Tuesday & Wednesday.',
    days: [
      {
        datetime: '2024-03-21',
        datetimeEpoch: 1710946800,
        tempmax: 2.8,
        tempmin: -0.5,
        temp: 1.4,
        feelslikemax: 1.5,
        feelslikemin: -4.3,
        feelslike: -1.2,
        dew: -3.6,
        humidity: 70,
        precip: 2.5,
        precipprob: 83.9,
        precipcover: 33.33,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 20.2,
        windspeed: 12.2,
        winddir: 330.2,
        pressure: 1008.5,
        cloudcover: 100,
        visibility: 20,
        solarradiation: 108.9,
        solarenergy: 9.5,
        uvindex: 4,
        severerisk: 10,
        sunrise: '05:36:43',
        sunriseEpoch: 1710967003,
        sunset: '17:48:16',
        sunsetEpoch: 1711010896,
        moonphase: 0.36,
        conditions: 'Snow, Rain, Overcast',
        description: 'Cloudy skies throughout the day with rain or snow clearing later.',
        icon: 'rain',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-03-22',
        datetimeEpoch: 1711033200,
        tempmax: 5,
        tempmin: 0.4,
        temp: 2.7,
        feelslikemax: 1,
        feelslikemin: -3.5,
        feelslike: -1.3,
        dew: -3.6,
        humidity: 64.1,
        precip: 0.4,
        precipprob: 35.5,
        precipcover: 16.67,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 31,
        windspeed: 24.5,
        winddir: 308.1,
        pressure: 1018,
        cloudcover: 93.6,
        visibility: 22,
        solarradiation: 206.5,
        solarenergy: 17.9,
        uvindex: 7,
        severerisk: 10,
        sunrise: '05:35:03',
        sunriseEpoch: 1711053303,
        sunset: '17:49:21',
        sunsetEpoch: 1711097361,
        moonphase: 0.39,
        conditions: 'Overcast',
        description: 'Cloudy skies throughout the day.',
        icon: 'cloudy',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-03-23',
        datetimeEpoch: 1711119600,
        tempmax: 5.7,
        tempmin: 1.5,
        temp: 3.8,
        feelslikemax: 2.8,
        feelslikemin: -2.3,
        feelslike: 0.7,
        dew: -1.7,
        humidity: 67.9,
        precip: 0,
        precipprob: 19.4,
        precipcover: 0,
        preciptype: null,
        snow: 0,
        snowdepth: null,
        windgust: 29.9,
        windspeed: 19.8,
        winddir: 168.8,
        pressure: 1020.3,
        cloudcover: 79.5,
        visibility: 24.1,
        solarradiation: 197.7,
        solarenergy: 17,
        uvindex: 7,
        severerisk: 10,
        sunrise: '05:33:22',
        sunriseEpoch: 1711139602,
        sunset: '17:50:26',
        sunsetEpoch: 1711183826,
        moonphase: 0.43,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-03-24',
        datetimeEpoch: 1711206000,
        tempmax: 7.2,
        tempmin: 3.8,
        temp: 5.8,
        feelslikemax: 4.3,
        feelslikemin: 0.2,
        feelslike: 2.3,
        dew: 2.5,
        humidity: 79.6,
        precip: 0.9,
        precipprob: 12.9,
        precipcover: 25,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 63.4,
        windspeed: 46.4,
        winddir: 274,
        pressure: 1015.3,
        cloudcover: 71.6,
        visibility: 23.8,
        solarradiation: 99.7,
        solarenergy: 8.8,
        uvindex: 5,
        severerisk: 10,
        sunrise: '05:31:42',
        sunriseEpoch: 1711225902,
        sunset: '17:51:30',
        sunsetEpoch: 1711270290,
        moonphase: 0.46,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-03-25',
        datetimeEpoch: 1711292400,
        tempmax: 7.3,
        tempmin: 4.3,
        temp: 5.5,
        feelslikemax: 3.6,
        feelslikemin: -1.5,
        feelslike: 1.3,
        dew: -1.2,
        humidity: 62.2,
        precip: 0.1,
        precipprob: 12.9,
        precipcover: 4.17,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 58,
        windspeed: 42.5,
        winddir: 279.4,
        pressure: 1020.5,
        cloudcover: 72.4,
        visibility: 24.1,
        solarradiation: 241.3,
        solarenergy: 20.7,
        uvindex: 8,
        severerisk: 10,
        sunrise: '05:30:01',
        sunriseEpoch: 1711312201,
        sunset: '17:52:34',
        sunsetEpoch: 1711356754,
        moonphase: 0.5,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-03-26',
        datetimeEpoch: 1711378800,
        tempmax: 5.9,
        tempmin: 2.4,
        temp: 4.5,
        feelslikemax: 1.4,
        feelslikemin: -3.6,
        feelslike: -0.4,
        dew: 2.7,
        humidity: 88.4,
        precip: 14.1,
        precipprob: 74.2,
        precipcover: 20.83,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 51.5,
        windspeed: 33.5,
        winddir: 106.6,
        pressure: 1013.4,
        cloudcover: 100,
        visibility: 13.3,
        solarradiation: 33.4,
        solarenergy: 3,
        uvindex: 1,
        severerisk: 10,
        sunrise: '05:28:21',
        sunriseEpoch: 1711398501,
        sunset: '17:53:39',
        sunsetEpoch: 1711443219,
        moonphase: 0.53,
        conditions: 'Rain, Overcast',
        description: 'Cloudy skies throughout the day with a chance of rain.',
        icon: 'rain',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-03-27',
        datetimeEpoch: 1711465200,
        tempmax: 7.5,
        tempmin: 1.9,
        temp: 4.3,
        feelslikemax: 4.4,
        feelslikemin: -3.9,
        feelslike: 0.3,
        dew: 1.3,
        humidity: 82.1,
        precip: 6.9,
        precipprob: 58.1,
        precipcover: 20.83,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 46.8,
        windspeed: 31.7,
        winddir: 275.2,
        pressure: 1015.2,
        cloudcover: 50.3,
        visibility: 16.1,
        solarradiation: 190.9,
        solarenergy: 16.5,
        uvindex: 7,
        severerisk: 10,
        sunrise: '05:26:41',
        sunriseEpoch: 1711484801,
        sunset: '17:54:43',
        sunsetEpoch: 1711529683,
        moonphase: 0.56,
        conditions: 'Snow, Rain, Partially cloudy',
        description: 'Clearing in the afternoon with early morning snow or rain.',
        icon: 'rain',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-03-28',
        datetimeEpoch: 1711551600,
        tempmax: 8,
        tempmin: 3.2,
        temp: 5.6,
        feelslikemax: 5.4,
        feelslikemin: -1.2,
        feelslike: 2.8,
        dew: 0.8,
        humidity: 71.7,
        precip: 0,
        precipprob: 16.1,
        precipcover: 0,
        preciptype: null,
        snow: 0,
        snowdepth: null,
        windgust: 34.2,
        windspeed: 21.2,
        winddir: 203.7,
        pressure: 1018.1,
        cloudcover: 68.4,
        visibility: 24.1,
        solarradiation: 226.9,
        solarenergy: 19.5,
        uvindex: 7,
        severerisk: 10,
        sunrise: '05:25:00',
        sunriseEpoch: 1711571100,
        sunset: '17:55:47',
        sunsetEpoch: 1711616147,
        moonphase: 0.6,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-03-29',
        datetimeEpoch: 1711638000,
        tempmax: 11.1,
        tempmin: 6.4,
        temp: 8.7,
        feelslikemax: 11.1,
        feelslikemin: 5.1,
        feelslike: 8.2,
        dew: 5.8,
        humidity: 82.2,
        precip: 1.7,
        precipprob: 32.3,
        precipcover: 16.67,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 17.6,
        windspeed: 11.3,
        winddir: 179.5,
        pressure: 1014.3,
        cloudcover: 65.1,
        visibility: 23.7,
        solarradiation: 194.6,
        solarenergy: 16.8,
        uvindex: 6,
        severerisk: 10,
        sunrise: '05:23:20',
        sunriseEpoch: 1711657400,
        sunset: '17:56:51',
        sunsetEpoch: 1711702611,
        moonphase: 0.63,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-03-30',
        datetimeEpoch: 1711724400,
        tempmax: 8.6,
        tempmin: 6.6,
        temp: 7.5,
        feelslikemax: 8,
        feelslikemin: 2.9,
        feelslike: 4.8,
        dew: 6.8,
        humidity: 95.2,
        precip: 2.5,
        precipprob: 35.5,
        precipcover: 8.33,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 56.9,
        windspeed: 34.2,
        winddir: 110.6,
        pressure: 1005.2,
        cloudcover: 98.3,
        visibility: 8.2,
        solarradiation: 49.3,
        solarenergy: 4.2,
        uvindex: 2,
        severerisk: 10,
        sunrise: '05:21:41',
        sunriseEpoch: 1711743701,
        sunset: '17:57:55',
        sunsetEpoch: 1711789075,
        moonphase: 0.67,
        conditions: 'Overcast',
        description: 'Cloudy skies throughout the day.',
        icon: 'cloudy',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-03-31',
        datetimeEpoch: 1711810800,
        tempmax: 8.1,
        tempmin: 4.5,
        temp: 6.3,
        feelslikemax: 3.5,
        feelslikemin: -0.3,
        feelslike: 1.4,
        dew: 1.9,
        humidity: 73.8,
        precip: 3.8,
        precipprob: 48.4,
        precipcover: 25,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 63.7,
        windspeed: 49.7,
        winddir: 261.7,
        pressure: 1001.8,
        cloudcover: 38.8,
        visibility: 20.8,
        solarradiation: 265.8,
        solarenergy: 22.5,
        uvindex: 8,
        severerisk: 10,
        sunrise: '05:20:01',
        sunriseEpoch: 1711830001,
        sunset: '17:58:59',
        sunsetEpoch: 1711875539,
        moonphase: 0.7,
        conditions: 'Rain, Partially cloudy',
        description: 'Partly cloudy throughout the day with morning rain.',
        icon: 'rain',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-04-01',
        datetimeEpoch: 1711897200,
        tempmax: 8.3,
        tempmin: 4.6,
        temp: 6.1,
        feelslikemax: 4.5,
        feelslikemin: -0.4,
        feelslike: 2.3,
        dew: -0.9,
        humidity: 61.4,
        precip: 2.4,
        precipprob: 32.3,
        precipcover: 16.67,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 51.8,
        windspeed: 35.6,
        winddir: 275.4,
        pressure: 1006.6,
        cloudcover: 49.9,
        visibility: 22.2,
        solarradiation: 249.8,
        solarenergy: 21.6,
        uvindex: 8,
        severerisk: 10,
        sunrise: '05:18:22',
        sunriseEpoch: 1711916302,
        sunset: '18:00:03',
        sunsetEpoch: 1711962003,
        moonphase: 0.74,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-04-02',
        datetimeEpoch: 1711983600,
        tempmax: 6.2,
        tempmin: 3.2,
        temp: 4.5,
        feelslikemax: 3.4,
        feelslikemin: 0.3,
        feelslike: 1.7,
        dew: 1,
        humidity: 78.2,
        precip: 2,
        precipprob: 12.9,
        precipcover: 20.83,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 30.6,
        windspeed: 25.6,
        winddir: 82.9,
        pressure: 1008.1,
        cloudcover: 93.8,
        visibility: 20.9,
        solarradiation: 120.9,
        solarenergy: 10.5,
        uvindex: 3,
        severerisk: 10,
        sunrise: '05:16:42',
        sunriseEpoch: 1712002602,
        sunset: '18:01:07',
        sunsetEpoch: 1712048467,
        moonphase: 0.75,
        conditions: 'Overcast',
        description: 'Cloudy skies throughout the day.',
        icon: 'cloudy',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-04-03',
        datetimeEpoch: 1712070000,
        tempmax: 7.6,
        tempmin: 2.6,
        temp: 5.1,
        feelslikemax: 3.6,
        feelslikemin: 0.2,
        feelslike: 1.5,
        dew: -0.5,
        humidity: 67.7,
        precip: 0.3,
        precipprob: 25.8,
        precipcover: 8.33,
        preciptype: [Array],
        snow: 0,
        snowdepth: null,
        windgust: 35.6,
        windspeed: 28.8,
        winddir: 285.7,
        pressure: 1016.7,
        cloudcover: 29.7,
        visibility: 24.1,
        solarradiation: 270.8,
        solarenergy: 23.4,
        uvindex: 8,
        severerisk: 10,
        sunrise: '05:15:04',
        sunriseEpoch: 1712088904,
        sunset: '18:02:10',
        sunsetEpoch: 1712134930,
        moonphase: 0.81,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: null,
        source: 'fcst',
        hours: [Array]
      },
      {
        datetime: '2024-04-04',
        datetimeEpoch: 1712156400,
        tempmax: 8.6,
        tempmin: 3.6,
        temp: 6.2,
        feelslikemax: 7.1,
        feelslikemin: 0.3,
        feelslike: 4.1,
        dew: 0.9,
        humidity: 69.3,
        precip: 0,
        precipprob: 22.6,
        precipcover: 0,
        preciptype: null,
        snow: 0,
        snowdepth: null,
        windgust: 29.9,
        windspeed: 19.4,
        winddir: 235,
        pressure: 1017.9,
        cloudcover: 95.5,
        visibility: 24.1,
        solarradiation: 196.9,
        solarenergy: 16.8,
        uvindex: 6,
        severerisk: 10,
        sunrise: '05:13:25',
        sunriseEpoch: 1712175205,
        sunset: '18:03:14',
        sunsetEpoch: 1712221394,
        moonphase: 0.84,
        conditions: 'Overcast',
        description: 'Cloudy skies throughout the day.',
        icon: 'cloudy',
        stations: null,
        source: 'fcst',
        hours: [Array]
      }
    ],
    alerts: [],
    stations: {
      RJCH: {
        distance: 87956,
        latitude: 41.77,
        longitude: 140.82,
        useCount: 0,
        id: 'RJCH',
        name: 'RJCH',
        quality: 30,
        contribution: 0
      },
      RJSH: {
        distance: 59614,
        latitude: 40.54,
        longitude: 141.47,
        useCount: 0,
        id: 'RJSH',
        name: 'RJSH',
        quality: 2,
        contribution: 0
      },
      RJSM: {
        distance: 40370,
        latitude: 40.7,
        longitude: 141.38,
        useCount: 0,
        id: 'RJSM',
        name: 'RJSM',
        quality: 50,
        contribution: 0
      }
    },
    currentConditions: {
      datetime: '00:00:00',
      datetimeEpoch: 1710946800,
      temp: -1.3,
      feelslike: -4.9,
      humidity: 79,
      dew: -4.5,
      precip: 0.6,
      precipprob: 83.9,
      snow: 0,
      snowdepth: 0,
      preciptype: [ 'rain', 'snow' ],
      windgust: null,
      windspeed: 10.2,
      winddir: 297,
      pressure: 1006.6,
      visibility: 8.6,
      cloudcover: 88,
      solarradiation: 0,
      solarenergy: 0,
      uvindex: 0,
      conditions: 'Snow, Partially cloudy',
      icon: 'snow',
      stations: [ 'RJSM', 'RJCH', 'RJSH' ],
      source: 'obs',
      sunrise: '05:36:43',
      sunriseEpoch: 1710967003,
      sunset: '17:48:16',
      sunsetEpoch: 1711010896,
      moonphase: 0.36
    }
  }
  [Done] exited with code=0 in 0.845 seconds*/